const siteBase = "https://macacolabs.github.io/baduk-trainer/";
const feedItemLimit = 50;

const publicPages = [
  "index.html",
  "about.html",
  "learn.html",
  "baduk-learn.html",
  "omok-learn.html",
  "faq.html",
  "privacy.html",
  "terms.html",
  "adsense-checklist.html",
  "search-console.html",
];

const articleFiles = [
  "baduk-beginner.html",
  "baduk-rules-order.html",
  "baduk-free-learn.html",
  "baduk-self-study.html",
  "baduk-9x9-beginner.html",
  "baduk-9x9-first-move.html",
  "baduk-9x9-ai-losses.html",
  "baduk-9x9-to-19x19.html",
  "baduk-13x13-start.html",
  "baduk-13x13-opening.html",
  "baduk-19x19-start.html",
  "baduk-rank-roadmap.html",
  "baduk-30k-to-20k.html",
  "baduk-beginner-mistakes.html",
  "baduk-atari.html",
  "baduk-atari-practice.html",
  "baduk-atari-response.html",
  "baduk-atari-loss.html",
  "baduk-problem-solving-order.html",
  "baduk-beginner-accuracy-rate.html",
  "baduk-ladder.html",
  "baduk-ladder-breaker.html",
  "baduk-net.html",
  "baduk-cut-connect.html",
  "baduk-attack-weak-stones.html",
  "baduk-profitable-capture.html",
  "baduk-save-or-sacrifice.html",
  "baduk-sacrifice-moments.html",
  "baduk-liberties.html",
  "baduk-self-atari.html",
  "baduk-shape-empty-triangle.html",
  "baduk-knight-move.html",
  "baduk-glossary.html",
  "baduk-ko-rule.html",
  "baduk-ko-fight-timing.html",
  "baduk-ko-threats.html",
  "baduk-opening.html",
  "baduk-first-50-moves.html",
  "baduk-19x19-early-fight.html",
  "baduk-opening-corner.html",
  "baduk-side-opening.html",
  "baduk-center-opening.html",
  "baduk-thickness-territory.html",
  "baduk-invasion-reduction.html",
  "baduk-position-judgment-start.html",
  "baduk-joseki-study.html",
  "baduk-ai-review.html",
  "baduk-ai-games-only.html",
  "baduk-1k-ai-review-time.html",
  "baduk-ai-difficulty.html",
  "baduk-candidate-moves.html",
  "baduk-reading-depth.html",
  "baduk-which-game-to-review.html",
  "baduk-review-note.html",
  "baduk-repeat-mistakes.html",
  "baduk-review-10-minute.html",
  "baduk-life-and-death.html",
  "baduk-large-group-death.html",
  "baduk-alive-dead-stones.html",
  "baduk-life-and-death-practice.html",
  "baduk-life-death-real-game.html",
  "baduk-life-death-10-minute-routine.html",
  "baduk-life-death-vital-point.html",
  "baduk-false-eye.html",
  "baduk-seki.html",
  "baduk-10k-losing-reasons.html",
  "baduk-10k-to-5k.html",
  "baduk-5k-to-1k.html",
  "baduk-1k-daily-routine.html",
  "baduk-1k-weekly-review.html",
  "baduk-territory-scoring.html",
  "baduk-scoring-order.html",
  "baduk-dead-stones-scoring.html",
  "baduk-neutral-points.html",
  "baduk-scoring-practice-start.html",
  "baduk-scoring-practice-guide.html",
  "baduk-komi-6-5.html",
  "baduk-endgame.html",
  "baduk-endgame-big-move.html",
  "baduk-endgame-point-size.html",
  "baduk-endgame-sente.html",
  "baduk-endgame-mistakes.html",
  "baduk-sente-gote.html",
  "baduk-beginner-tenuki.html",
  "baduk-tenuki-timing.html",
  "omok-strategy.html",
  "omok-beginner-losing-patterns.html",
  "omok-winning-strategy.html",
  "omok-center-opening.html",
  "omok-after-first-move.html",
  "omok-first-second.html",
  "omok-first-player-win.html",
  "omok-respond-center.html",
  "omok-second-player-counterattack.html",
  "omok-first-10-moves.html",
  "omok-two-stones.html",
  "omok-forbidden-moves.html",
  "omok-double-three-four.html",
  "omok-forbidden-real-game.html",
  "omok-renju-black-disadvantage.html",
  "omok-six-in-a-row.html",
  "omok-threats.html",
  "omok-reading-depth.html",
  "omok-double-threat.html",
  "omok-defend-double-threat.html",
  "omok-one-side-block-late.html",
  "omok-attack-defense-priority.html",
  "omok-attack-timing.html",
  "omok-when-to-defend.html",
  "omok-defense-to-attack.html",
  "omok-counterattack-after-block.html",
  "omok-block-four.html",
  "omok-four-blocked.html",
  "omok-after-block-four-loss.html",
  "omok-block-four-checklist.html",
  "omok-defense-practice.html",
  "omok-blocking-point.html",
  "omok-open-four.html",
  "omok-open-three.html",
  "omok-before-three.html",
  "omok-open-three-losing.html",
  "omok-after-block-open-three-loss.html",
  "omok-closed-three.html",
  "omok-three-vs-four.html",
  "omok-ai-difficulty.html",
  "omok-ai-losing-reasons.html",
  "omok-difficulty-choice.html",
  "omok-level-up-timing.html",
  "omok-hard-ai-losses.html",
  "omok-practice-routine.html",
  "omok-review-mistakes.html",
];

const badukArticleFiles = articleFiles.filter((file) => file.startsWith("baduk-"));
const omokArticleFiles = articleFiles.filter((file) => file.startsWith("omok-"));
const learnItemListFiles = Array.from(new Set([
  ...badukArticleFiles.slice(0, 20),
  ...badukArticleFiles.slice(-8),
  ...omokArticleFiles.slice(0, 12),
  ...omokArticleFiles.slice(-6),
]));

const requiredPublicPages = publicPages;

const sitemapPages = [
  "privacy.html",
  "terms.html",
  "learn.html",
  "baduk-learn.html",
  "omok-learn.html",
  "faq.html",
  "about.html",
  "adsense-checklist.html",
  "search-console.html",
  ...articleFiles,
];

module.exports = {
  articleFiles,
  feedItemLimit,
  learnItemListFiles,
  publicPages,
  requiredPublicPages,
  siteBase,
  sitemapPages,
};
